### ISSUE TITLE
Schema errors on sample haa scripts??

### ISSUE THREAD

**Issue by cavanaug** [RavenSystem/meplhaa-editor#2]
Is the schema defined in this repo the canonical source??   I tried it with one of the sample meplhaa scripts from the device database for the geekbes and im getting schema errors.    Im using the latest version of the check-jsonschema python with the latest python library.

╭─[wsl:Ubuntu-22.04]─[git: (main)]─[cavanaug@jpc-zbook17:~/src_cavanaug/meplhaa-editor/haa-cavanaug/samples]
╰─[18:04:53]── check-jsonschema -vvv --traceback-mode full --schemafile ../../meplhaa.json geekbes.json
Schema validation errors were encountered.
  geekbes.json::$.c.b[0]: Additional properties are not allowed ('g', 't' were unexpected)

╭─[wsl:Ubuntu-22.04]─[git: (main)]─[cavanaug@jpc-zbook17:~/src_cavanaug/meplhaa-editor/haa-cavanaug/samples]
╰─[XX]─[18:05:00]── cat geekbes.json
{"c":{"l":1,"b":[{"g":3,"t":5}]},"a":[{"t":2,"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"es":[{"t":2,"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]}},{"t":2,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]}},{"t":2,"0":{"r":[{"g":13}]},"1":{"r":[{"g":13,"v":1}]}},{"0":{"r":[{"g":14}]},"1":{"r":[{"g":14,"v":1}]}}]}]}
╭─

**Comment by hennessyevan** [comment]
No it's a work in progress! Haven't had a ton of time to work on it lately but definitely not canonical.

**Comment by cavanaug** [comment]
You can close this issue.    I submitted some code changes that RavenSystem merged.   The schema validates all the sample scripts Ive been able to feed it.   Its a good validation tool.   Not so sure about the editor, but definitely a good validation mechanism.
